image:
  - ubuntu1804
  - Visual Studio 2015
environment:
  matrix:
    - PY_DIR: "C:\\Python27"
      DELUGE_VERSION: 1
    - PY_DIR: "C:\\Python27"
      DELUGE_VERSION: 2
    - PY_DIR: "C:\\Python36"
      DELUGE_VERSION: 1
    - PY_DIR: "C:\\Python36"
      DELUGE_VERSION: 2
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5sdWdUg0eZmrf/n3Sj9NwNa5nDfvokaPGJAbPNpHX4l5vCJDbiBIVh4Q479Gk8mxqdz+gNwQvHepmVwJ6g/ZrqyDZ4wQLnpkOjh4l7jKOwKjdA9mxdABm4aNNTkCjCFOQj4d1X0Me5D9y7Hoswae9VqBVOGFQSHDJoX0YQZADwGJgJ1cecS3zLT73XpF+NhVnamkacmCicPvIJP2ROef2ZDirXLU2fruh66d8mfApJ5SsmIzAdErivoQA/ZqrtiomuA7j1abCaJMAWNCxjYPHv7LwHbuTxYYg1Tz4oobvtoDTdzEwd8OwllFduzGzxfOQ87s6qErk6S/+CsNNf4+h john

for:
  -
    matrix:
      only:
        - DELUGE_VERSION: 1
    install:
      - cmd: choco install deluge --version=1.3.15
      - sh: sudo apt-get install deluged -y
  -
    matrix:
      only:
        - DELUGE_VERSION: 2
    install:
      - cmd: appveyor DownloadFile http://download.deluge-torrent.org/2.0/deluge-2.0b1-win32-setup.exe
      - cmd: deluge-2.0b1-win32-setup.exe /S
      - sh: sudo add-apt-repository ppa:deluge-team/develop -y
      - sh: sudo apt-get -qq update
      - sh: sudo apt-get install deluged -y
  -
    matrix:
      only:
        - PY_DIR: "C:\\Python27"
    stack: python 2.7
  -
    matrix:
      only:
        - PY_DIR: "C:\\Python36"
    stack: python 3.6


build: off

init:
- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

before_test:
  # For some reason we have to create the logfile first
  - ps: "if ($isWindows) {New-Item -Path 'C:\\Users\\appveyor\\AppData\\Roaming\\deluge' -ItemType Directory}"
  - ps: "if ($isWindows) {Start-Process \"c:\\Program Files (x86)\\Deluge\\deluged.exe\"}"
  - sh: /usr/bin/deluged
  - cmd: pip install pytest
  - sh: sudo pip install pytest
  # Give deluged a chance to start
  - ps: "Start-Sleep -s 10"

test_script:
  - pytest

on_failure:
  # Print the deluged log file to help debug problems
  - cmd: "type C:\\Users\\appveyor\\AppData\\Roaming\\deluge\\deluged.log"
